<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>assinador_pmenos</AssemblyName>
    <RootNamespace>AssinadorP7s</RootNamespace>
    <ApplicationManifest>src\app.manifest</ApplicationManifest>
    <ApplicationIcon>src\assets\assinador_pmenos.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="src\assets\assinador_pmenos.ico" />
    <Content Include="src\assets\assinador_pmenos_icon.png" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="8.0.1" />
  </ItemGroup>
</Project>
